// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts(name, currency, account_type)
VALUES($1, $2, $3)
RETURNING id, name, currency, account_type, created_at
`

type CreateAccountParams struct {
	Name        string `json:"name"`
	Currency    string `json:"currency"`
	AccountType string `json:"account_type"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.Currency, arg.AccountType)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, currency, account_type, created_at from accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT SUM(
	CASE WHEN direction = 'debit'
	THEN amount_cents
	ELSE -amount_cents
	END
) AS balance 
from entries
WHERE account_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, accountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}
