// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts(name, currency, account_type)
VALUES($1, $2, $3)
RETURNING id, name, currency, account_type, created_at
`

type CreateAccountParams struct {
	Name        string `json:"name"`
	Currency    string `json:"currency"`
	AccountType string `json:"account_type"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.Currency, arg.AccountType)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, currency, account_type, created_at from accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountHistory = `-- name: GetAccountHistory :many
SELECT transactions.description, entries.amount_cents, entries.direction, entries.created_at
from entries
INNER JOIN accounts
ON accounts.id = entries.account_id
INNER JOIN transactions
ON entries.transaction_id = transactions.id
WHERE entries.account_id = $1 
ORDER BY entries.created_at DESC
`

type GetAccountHistoryRow struct {
	Description string    `json:"description"`
	AmountCents int64     `json:"amount_cents"`
	Direction   string    `json:"direction"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetAccountHistory(ctx context.Context, accountID uuid.UUID) ([]GetAccountHistoryRow, error) {
	rows, err := q.db.Query(ctx, getAccountHistory, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountHistoryRow
	for rows.Next() {
		var i GetAccountHistoryRow
		if err := rows.Scan(
			&i.Description,
			&i.AmountCents,
			&i.Direction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalance = `-- name: GetBalance :one
SELECT 
COALESCE(
SUM(
	CASE WHEN direction = 'debit'
	THEN amount_cents
	ELSE -amount_cents
	END), 0
)::bigint AS balance 
from entries
WHERE account_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, accountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}
