// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries(transaction_id, account_id, amount_cents, currency, direction)
VALUES($1, $2, $3, $4, $5)
RETURNING id, transaction_id, account_id, amount_cents, currency, direction, created_at
`

type CreateEntryParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountID     uuid.UUID `json:"account_id"`
	AmountCents   int64     `json:"amount_cents"`
	Currency      string    `json:"currency"`
	Direction     string    `json:"direction"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.TransactionID,
		arg.AccountID,
		arg.AmountCents,
		arg.Currency,
		arg.Direction,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.AmountCents,
		&i.Currency,
		&i.Direction,
		&i.CreatedAt,
	)
	return i, err
}

const getEntires = `-- name: GetEntires :many
SELECT id, transaction_id, account_id, amount_cents, currency, direction, created_at from entries WHERE transaction_id = $1
`

func (q *Queries) GetEntires(ctx context.Context, transactionID uuid.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, getEntires, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.AmountCents,
			&i.Currency,
			&i.Direction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
