// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions(description, idempotency_key, occurred_at)
VALUES($1, $2, $3)
RETURNING id, description, idempotency_key, occurred_at, created_at
`

type CreateTransactionParams struct {
	Description    string    `json:"description"`
	IdempotencyKey string    `json:"idempotency_key"`
	OccurredAt     time.Time `json:"occurred_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.Description, arg.IdempotencyKey, arg.OccurredAt)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, description, idempotency_key, occurred_at, created_at from transactions WHERE idempotency_key  = $1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}
